import type { FilterPreset } from '../types';

export const FILTER_PRESETS: FilterPreset[] = [
  {
    id: 'normal',
    name: 'Gốc (Normal)',
    description: 'Không áp dụng bộ lọc màu',
    category: 'classic',
    adjustments: {},
  },
  {
    id: 'vivid',
    name: 'Vivid (Rực rỡ)',
    description: 'Tăng độ bão hòa, tương phản cao, màu sắc sống động',
    category: 'classic',
    adjustments: {
      saturation: 35,
      contrast: 20,
      clarity: 15,
      vignette: 10,
    },
  },
  {
    id: 'film-classic',
    name: 'Film Classic',
    description: 'Màu film analog kinh điển, tone màu cân bằng ấm áp',
    category: 'vintage',
    adjustments: {
      temperature: 12,
      contrast: 10,
      exposure: 5,
      shadows: 15,
      vignette: 18,
      blackPoint: 15,
    },
  },
  {
    id: 'vintage-70s',
    name: 'Vintage 1970',
    description: 'Phong cách retro thập niên 70, ngả vàng hổ phách',
    category: 'vintage',
    adjustments: {
      temperature: 28,
      tint: 8,
      contrast: -8,
      saturation: -10,
      blackPoint: 22,
      vignette: 25,
    },
  },
  {
    id: 'cinematic',
    name: 'Cinematic Teal & Orange',
    description: 'Tone màu điện ảnh Hollywood: đổ bóng xanh teal và da cam ấm',
    category: 'cinematic',
    adjustments: {
      contrast: 24,
      saturation: 15,
      temperature: -10,
      tint: -6,
      clarity: 20,
      vignette: 20,
    },
  },
  {
    id: 'noir',
    name: 'Noir B&W',
    description: 'Đen trắng điện ảnh sâu thẳm, tương phản mạnh mẽ',
    category: 'classic',
    adjustments: {
      saturation: -100,
      contrast: 35,
      exposure: -5,
      clarity: 25,
      vignette: 30,
      blackPoint: 10,
    },
  },
  {
    id: 'high-contrast-mono',
    name: 'Mono Graphic',
    description: 'Đen trắng đồ họa sắc nét, làm nổi bật đường nét',
    category: 'classic',
    adjustments: {
      saturation: -100,
      contrast: 55,
      sharpness: 30,
      highlights: 20,
      shadows: -20,
    },
  },
  {
    id: 'warm-sunset',
    name: 'Hoàng hôn (Sunset)',
    description: 'Ánh nắng hoàng hôn vàng cam lãng mạn',
    category: 'moody',
    adjustments: {
      temperature: 42,
      tint: 14,
      brightness: 5,
      saturation: 20,
      highlights: -15,
      shadows: 10,
      vignette: 15,
    },
  },
  {
    id: 'cool-breeze',
    name: 'Gió lạnh (Cool Breeze)',
    description: 'Tông lam ngọc thanh mát, dịu mắt và trong trẻo',
    category: 'moody',
    adjustments: {
      temperature: -35,
      tint: -12,
      brightness: 8,
      contrast: 10,
      clarity: 15,
    },
  },
  {
    id: 'fade-matte',
    name: 'Fade (Mờ ảo)',
    description: 'Nâng sáng vùng tối, hiệu ứng ảnh in tạp chí mờ lì',
    category: 'vintage',
    adjustments: {
      contrast: -25,
      brightness: 10,
      blackPoint: 35,
      saturation: -15,
    },
  },
  {
    id: 'dramatic-dark',
    name: 'Dramatic Dark',
    description: 'Hắc ám kịch tính, vùng tối sâu, sắc nét cao',
    category: 'cinematic',
    adjustments: {
      exposure: -15,
      contrast: 40,
      shadows: -35,
      clarity: 35,
      vignette: 40,
    },
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk Neon',
    description: 'Sắc tím neon kết hợp ánh xanh tương lai rực sáng',
    category: 'creative',
    adjustments: {
      contrast: 30,
      saturation: 45,
      temperature: -25,
      tint: 35,
      clarity: 30,
      vignette: 25,
    },
  },
  {
    id: 'sepia',
    name: 'Sepia Cổ điển',
    description: 'Nâu cổ kính hoài niệm của những bức ảnh thời xưa',
    category: 'vintage',
    adjustments: {
      saturation: -45,
      temperature: 55,
      tint: 20,
      contrast: 5,
      vignette: 30,
      blackPoint: 15,
    },
  },
  {
    id: 'emerald',
    name: 'Emerald (Ngọc bích)',
    description: 'Tôn vinh sắc xanh cây cỏ thiên nhiên tươi mát',
    category: 'moody',
    adjustments: {
      temperature: -10,
      tint: -22,
      saturation: 25,
      contrast: 15,
      clarity: 15,
    },
  },
  {
    id: 'golden-hour',
    name: 'Golden Hour',
    description: 'Khoảnh khắc vàng của ánh sáng tự nhiên rạng rỡ',
    category: 'moody',
    adjustments: {
      temperature: 30,
      brightness: 10,
      contrast: 12,
      highlights: -10,
      shadows: 15,
      saturation: 18,
    },
  },
  {
    id: 'moody-film',
    name: 'Moody Film',
    description: 'Phong cách điện ảnh u buồn, độ bão hòa thấp, trầm lắng',
    category: 'cinematic',
    adjustments: {
      saturation: -25,
      contrast: 18,
      exposure: -8,
      shadows: -15,
      temperature: -8,
      tint: -10,
      vignette: 35,
    },
  },
  {
    id: 'pastel-dream',
    name: 'Pastel Dream',
    description: 'Mộng mơ, tone màu phấn nhẹ nhàng, sáng và êm dịu',
    category: 'creative',
    adjustments: {
      brightness: 18,
      contrast: -15,
      saturation: 10,
      highlights: -20,
      shadows: 30,
      blackPoint: 20,
    },
  },
  {
    id: 'polaroid',
    name: 'Polaroid Instant',
    description: 'Ảnh chụp lấy liền Polaroid với tone ấm và viền tối nhẹ',
    category: 'vintage',
    adjustments: {
      temperature: 20,
      contrast: 8,
      brightness: 12,
      shadows: 20,
      blackPoint: 25,
      vignette: 28,
    },
  },
];
